# Generated by Django 5.0.1 on 2024-09-16 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket_app", "0002_ticket_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="user",
        ),
        migrations.AddField(
            model_name="ticket",
            name="buyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="tickets_bought",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="seller",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets_sold",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
